# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gilles/previous/previous

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gilles/previous/previous

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gilles/previous/previous/CMakeFiles /home/gilles/previous/previous/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gilles/previous/previous/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named previous

# Build rule for target.
previous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 previous
.PHONY : previous

# fast build rule for target.
previous/fast:
	$(MAKE) -f src/CMakeFiles/previous.dir/build.make src/CMakeFiles/previous.dir/build
.PHONY : previous/fast

#=============================================================================
# Target rules for targets named Debug

# Build rule for target.
Debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Debug
.PHONY : Debug

# fast build rule for target.
Debug/fast:
	$(MAKE) -f src/debug/CMakeFiles/Debug.dir/build.make src/debug/CMakeFiles/Debug.dir/build
.PHONY : Debug/fast

#=============================================================================
# Target rules for targets named GuiSdl

# Build rule for target.
GuiSdl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GuiSdl
.PHONY : GuiSdl

# fast build rule for target.
GuiSdl/fast:
	$(MAKE) -f src/gui-sdl/CMakeFiles/GuiSdl.dir/build.make src/gui-sdl/CMakeFiles/GuiSdl.dir/build
.PHONY : GuiSdl/fast

#=============================================================================
# Target rules for targets named UaeCpu

# Build rule for target.
UaeCpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UaeCpu
.PHONY : UaeCpu

# fast build rule for target.
UaeCpu/fast:
	$(MAKE) -f src/uae-cpu/CMakeFiles/UaeCpu.dir/build.make src/uae-cpu/CMakeFiles/UaeCpu.dir/build
.PHONY : UaeCpu/fast

#=============================================================================
# Target rules for targets named build68k

# Build rule for target.
build68k: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build68k
.PHONY : build68k

# fast build rule for target.
build68k/fast:
	$(MAKE) -f src/uae-cpu/CMakeFiles/build68k.dir/build.make src/uae-cpu/CMakeFiles/build68k.dir/build
.PHONY : build68k/fast

#=============================================================================
# Target rules for targets named gencpu

# Build rule for target.
gencpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gencpu
.PHONY : gencpu

# fast build rule for target.
gencpu/fast:
	$(MAKE) -f src/uae-cpu/CMakeFiles/gencpu.dir/build.make src/uae-cpu/CMakeFiles/gencpu.dir/build
.PHONY : gencpu/fast

#=============================================================================
# Target rules for targets named hatariui_man

# Build rule for target.
hatariui_man: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hatariui_man
.PHONY : hatariui_man

# fast build rule for target.
hatariui_man/fast:
	$(MAKE) -f python-ui/CMakeFiles/hatariui_man.dir/build.make python-ui/CMakeFiles/hatariui_man.dir/build
.PHONY : hatariui_man/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... distclean"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... previous"
	@echo "... Debug"
	@echo "... GuiSdl"
	@echo "... UaeCpu"
	@echo "... build68k"
	@echo "... gencpu"
	@echo "... hatariui_man"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

